name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-py-modules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -e .[dev]

    - name: Run isort
      run: isort . --check-only --diff

    - name: Run black
      run: black . --check

    - name: Run pylint
      run: pylint .

    - name: Run pytest
      run: pytest .

  test-example-script:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install .

    - name: Execute example script
      run: ./tests/test_cli.sh
